[project]
name = "simple-reputation-system"
description = "A simple reputation system for rating users on blockchain"
authors = ["Developer"]
telemetry = false
cache_dir = "./.cache"
requirements = []

[contracts.reputation-system]
path = "contracts/reputation-system.clar"
clarity_version = 2
epoch = 2.4

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
